# questions.py

# ------------------- TECHNICAL ROLES -------------------

TECHNICAL_QUESTIONS = {

    "Python Developer": [
        # 25 MCQs
        ("Which of the following is a mutable data type in Python?", ["List", "Tuple", "String", "Integer"], "List"),
        ("Which keyword is used to create a function in Python?", ["func", "def", "function", "lambda"], "def"),
        ("What does PEP stand for in Python?", ["Python Enhancement Proposal", "Python Easy Program", "Python Example Paper", "Program Enhancement Proposal"], "Python Enhancement Proposal"),
        ("Which of these is a Python loop type?", ["for", "loop", "iterate", "repeat"], "for"),
        ("Which operator is used for integer division in Python?", ["/", "//", "%", "**"], "//"),
        ("What is the output of print(2**3)?", ["5", "8", "6", "9"], "8"),
        ("Which of the following is a Python dictionary method?", ["append()", "keys()", "insert()", "add()"], "keys()"),
        ("How do you handle exceptions in Python?", ["try-except", "catch", "handle", "error"], "try-except"),
        ("Which keyword is used to create a class?", ["class", "def", "object", "struct"], "class"),
        ("Which of these is immutable?", ["List", "Tuple", "Dictionary", "Set"], "Tuple"),
        ("What is the output of len([1,2,3,4])?", ["3","4","5","2"], "4"),
        ("What does the 'pass' statement do?", ["Does nothing", "Exits loop", "Returns value", "Throws error"], "Does nothing"),
        ("Which module is used to work with JSON in Python?", ["json", "pickle", "os", "sys"], "json"),
        ("Which keyword creates an anonymous function?", ["lambda", "def", "func", "anon"], "lambda"),
        ("Which is correct syntax to import math module?", ["import math", "include math", "require math", "use math"], "import math"),
        ("Which of the following is not a Python data type?", ["List", "Tuple", "Set", "ArrayList"], "ArrayList"),
        ("Which method converts string to lowercase?", ["lower()", "toLower()", "downcase()", "small()"], "lower()"),
        ("What does 'self' refer to in Python classes?", ["Current object", "Parent object", "Global object", "Module"], "Current object"),
        ("Which statement is used to exit a loop?", ["exit", "break", "continue", "stop"], "break"),
        ("What is the output of print(bool(0))?", ["True", "False", "0", "1"], "False"),
        ("Which function returns the largest item in a list?", ["max()", "min()", "largest()", "top()"], "max()"),
        ("Which operator is used to check equality?", ["=", "==", "!=", "<>"], "=="),
        ("Which of these is a Python set method?", ["add()", "append()", "push()", "insert()"], "add()"),
        ("Which method removes an item from a list?", ["remove()", "delete()", "pop()", "discard()"], "remove()"),
        ("Which of the following is used to create virtual environments?", ["venv", "pip", "virtual", "envcreate"], "venv"),

        # 25 Descriptive Questions
        ("Explain what a Python list is.", None, None),
        ("Describe the difference between list and tuple.", None, None),
        ("Explain Python dictionary and its uses.", None, None),
        ("Describe exception handling in Python.", None, None),
        ("Explain the concept of functions in Python.", None, None),
        ("What are Python modules and how are they used?", None, None),
        ("Explain the difference between shallow copy and deep copy.", None, None),
        ("Describe the use of *args and **kwargs.", None, None),
        ("Explain Python class and object creation.", None, None),
        ("Describe inheritance in Python.", None, None),
        ("Explain polymorphism with an example.", None, None),
        ("Describe encapsulation in Python.", None, None),
        ("Explain Python decorators and their uses.", None, None),
        ("Describe generators in Python.", None, None),
        ("Explain list comprehensions with an example.", None, None),
        ("What are Python iterators?", None, None),
        ("Explain Python's global and local scope.", None, None),
        ("Describe Python's built-in data structures.", None, None),
        ("Explain Python's file handling operations.", None, None),
        ("Describe Python's lambda function with an example.", None, None),
        ("Explain Python's map(), filter(), and reduce().", None, None),
        ("Describe Python's set operations.", None, None),
        ("Explain exception types in Python.", None, None),
        ("Describe Python's string methods with examples.", None, None),
        ("Explain Python's object lifecycle.", None, None),
    ],

    "Data Scientist": [
        # 25 MCQs
        ("Which library is commonly used for data manipulation in Python?", ["numpy", "pandas", "matplotlib", "seaborn"], "pandas"),
        ("Which function shows the first 5 rows of a DataFrame?", ["head()", "top()", "show()", "first()"], "head()"),
        ("Which of these is a plotting library?", ["numpy", "pandas", "matplotlib", "sklearn"], "matplotlib"),
        ("What is supervised learning?", ["Using labeled data", "Using unlabeled data", "Using random data", "No data"], "Using labeled data"),
        ("Which method is used for linear regression in sklearn?", ["LinearRegression()", "LogisticRegression()", "Regress()", "Fit()"], "LinearRegression()"),
        ("What does 'NaN' stand for?", ["Not a Number", "No Assignment Needed", "Null as Number", "Number not Available"], "Not a Number"),
        ("Which method fills missing values?", ["fillna()", "replace()", "dropna()", "remove()"], "fillna()"),
        ("Which is a Python ML library?", ["matplotlib", "sklearn", "pandas", "numpy"], "sklearn"),
        ("Which method splits dataset into train and test?", ["train_test_split()", "split()", "divide()", "partition()"], "train_test_split()"),
        ("Which metric is used for classification?", ["Accuracy", "MSE", "RMSE", "Variance"], "Accuracy"),
        ("Which metric is used for regression?", ["Accuracy", "MSE", "RMSE", "R2"], "MSE"),
        ("Which function is used to read CSV in pandas?", ["read_csv()", "load_csv()", "open_csv()", "readfile()"], "read_csv()"),
        ("Which of these is used for data visualization?", ["sklearn", "numpy", "matplotlib", "os"], "matplotlib"),
        ("Which library is used for statistical operations?", ["numpy", "scipy", "matplotlib", "pandas"], "scipy"),
        ("Which method calculates correlation?", ["corr()", "cov()", "correlation()", "calc()"], "corr()"),
        ("Which is an unsupervised learning algorithm?", ["KMeans", "Linear Regression", "Logistic Regression", "Decision Tree"], "KMeans"),
        ("Which method normalizes data?", ["scale()", "normalize()", "standardize()", "fit()"], "normalize()"),
        ("Which function computes mean?", ["mean()", "average()", "avg()", "mid()"], "mean()"),
        ("Which function computes median?", ["median()", "med()", "middle()", "avg()"], "median()"),
        ("Which is used for one-hot encoding?", ["LabelEncoder", "OneHotEncoder", "OrdinalEncoder", "Scaler"], "OneHotEncoder"),
        ("Which metric is used for clustering evaluation?", ["Silhouette", "Accuracy", "RMSE", "R2"], "Silhouette"),
        ("Which is used to handle categorical data?", ["LabelEncoder", "StandardScaler", "MinMaxScaler", "PCA"], "LabelEncoder"),
        ("Which is a Python library for NLP?", ["nltk", "pandas", "numpy", "matplotlib"], "nltk"),
        ("Which Python library is used for deep learning?", ["tensorflow", "pandas", "sklearn", "matplotlib"], "tensorflow"),
        ("Which is a common loss function for regression?", ["MSE", "CrossEntropy", "Hinge", "LogLoss"], "MSE"),

        # 25 Descriptive Questions
        ("Explain what a DataFrame is.", None, None),
        ("Describe differences between Series and DataFrame.", None, None),
        ("Explain supervised and unsupervised learning.", None, None),
        ("Describe linear regression with an example.", None, None),
        ("Explain logistic regression and its use.", None, None),
        ("Describe KMeans clustering.", None, None),
        ("Explain decision trees in machine learning.", None, None),
        ("Describe random forest algorithm.", None, None),
        ("Explain cross-validation.", None, None),
        ("Describe feature scaling.", None, None),
        ("Explain PCA and dimensionality reduction.", None, None),
        ("Describe bias-variance tradeoff.", None, None),
        ("Explain evaluation metrics for classification.", None, None),
        ("Describe evaluation metrics for regression.", None, None),
        ("Explain overfitting and underfitting.", None, None),
        ("Describe train-test split importance.", None, None),
        ("Explain correlation vs causation.", None, None),
        ("Describe handling missing data.", None, None),
        ("Explain one-hot encoding.", None, None),
        ("Describe NLP preprocessing steps.", None, None),
        ("Explain tokenization in NLP.", None, None),
        ("Describe word embeddings.", None, None),
        ("Explain sentiment analysis basics.", None, None),
        ("Describe model deployment steps.", None, None),
        ("Explain hyperparameter tuning.", None, None),
    ],

    # You would continue similarly for:
    # Web Developer, Machine Learning Engineer, AI Engineer, Cloud Engineer
    # For brevity, these are not fully expanded here, but the same pattern applies:
    # 25 MCQs + 25 Descriptive questions for each role.
}

# ------------------- NON-TECHNICAL ROLES -------------------

NON_TECHNICAL_QUESTIONS = {

    "HR Executive": [
        # 25 MCQs
        ("Which activity is part of recruitment?", ["Screening","Coding","Designing","Testing"], "Screening"),
        ("Which is a soft skill important for HR?", ["Communication","Python","HTML","SQL"], "Communication"),
        ("Which process involves employee onboarding?", ["Recruitment","Onboarding","Training","Exit"], "Onboarding"),
        ("Which HR metric measures employee leaving?", ["Attrition","Retention","Engagement","Satisfaction"], "Attrition"),
        ("Which system stores employee info?", ["HRIS","CRM","ERP","CMS"], "HRIS"),
        ("Which activity involves payroll?", ["Salary calculation","Hiring","Training","Marketing"], "Salary calculation"),
        ("Which is part of performance appraisal?", ["Reviewing goals","Coding","Designing","Selling"], "Reviewing goals"),
        ("Which is a key responsibility of HR?", ["Recruitment","Develop ML model","Design website","Manage finances"], "Recruitment"),
        ("Which skill helps in conflict management?", ["Negotiation","Python","HTML","Excel"], "Negotiation"),
        ("Which activity involves handling grievances?", ["Conflict resolution","Coding","Marketing","Testing"], "Conflict resolution"),
        ("Which method measures employee satisfaction?", ["Survey","Testing","Deployment","Analysis"], "Survey"),
        ("Which is part of training programs?", ["Workshops","Design","Coding","Testing"], "Workshops"),
        ("Which metric measures engagement?", ["Employee feedback","Python code","Website visits","Customer retention"], "Employee feedback"),
        ("Which activity involves HR compliance?", ["Policies","Design","Testing","Sales"], "Policies"),
        ("Which process includes HR audits?", ["Compliance check","Coding","Marketing","Design"], "Compliance check"),
        ("Which soft skill is vital for HR?", ["Communication","Python","Excel","SQL"], "Communication"),
        ("Which is part of employee retention?", ["Recognition","Coding","Testing","Design"], "Recognition"),
        ("Which is part of recruitment interview?", ["Screening","Coding","Testing","Debugging"], "Screening"),
        ("Which is part of succession planning?", ["Talent review","Website design","Python coding","Deployment"], "Talent review"),
        ("Which is part of employee engagement?", ["Team events","Python coding","Designing","Testing"], "Team events"),
        ("Which is part of HR reporting?", ["Metrics","Coding","Designing","Marketing"], "Metrics"),
        ("Which helps in employee evaluation?", ["360-degree feedback","Coding","Designing","Testing"], "360-degree feedback"),
        ("Which is part of HR analytics?", ["Attrition prediction","Coding","Testing","Marketing"], "Attrition prediction"),
        ("Which is a legal compliance HR activity?", ["Labor law adherence","Coding","Designing","Testing"], "Labor law adherence"),
        ("Which involves HR policy review?", ["Policy update","Coding","Designing","Testing"], "Policy update"),

        # 25 Descriptive
        ("Explain the recruitment process.", None, None),
        ("Describe employee onboarding.", None, None),
        ("Explain performance appraisal.", None, None),
        ("Describe employee engagement strategies.", None, None),
        ("Explain handling grievances.", None, None),
        ("Describe succession planning.", None, None),
        ("Explain HRIS system.", None, None),
        ("Describe training and development programs.", None, None),
        ("Explain talent acquisition strategies.", None, None),
        ("Describe HR metrics used for evaluation.", None, None),
        ("Explain conflict resolution techniques.", None, None),
        ("Describe the importance of communication in HR.", None, None),
        ("Explain payroll processing.", None, None),
        ("Describe HR compliance.", None, None),
        ("Explain legal adherence in HR.", None, None),
        ("Describe employee satisfaction measurement.", None, None),
        ("Explain attrition rate calculation.", None, None),
        ("Describe onboarding checklist.", None, None),
        ("Explain leadership development programs.", None, None),
        ("Describe team-building activities.", None, None),
        ("Explain HR reporting.", None, None),
        ("Describe compensation and benefits.", None, None),
        ("Explain performance feedback mechanisms.", None, None),
        ("Describe employee motivation techniques.", None, None),
        ("Explain HR analytics applications.", None, None),
    ],

    # Similarly continue for:
    # Business Analyst, Digital Marketing Executive, Content Writer, Customer Support Executive, Operations Executive
    # Each having 25 MCQs + 25 Descriptive questions
}
# ------------------- REMAINING TECHNICAL ROLES -------------------

TECHNICAL_QUESTIONS.update({

    "Web Developer": [
        # 25 MCQs
        ("Which language is used for styling web pages?", ["HTML","Python","CSS","Java"], "CSS"),
        ("Which tag is used for inserting an image in HTML?", ["<img>","<image>","<src>","<picture>"], "<img>"),
        ("Which JavaScript function is used to parse JSON?", ["JSON.parse()","JSON.load()","JSON.stringify()","JSON.read()"], "JSON.parse()"),
        ("Which of these is a JavaScript framework?", ["React","Django","Flask","TensorFlow"], "React"),
        ("What does CSS stand for?", ["Cascading Style Sheets","Computer Style Sheets","Creative Style Syntax","Coded Style Sheets"], "Cascading Style Sheets"),
        ("Which HTML tag is for creating a hyperlink?", ["<a>","<link>","<url>","<href>"], "<a>"),
        ("Which property changes text color in CSS?", ["color","font-color","text-color","style-color"], "color"),
        ("Which JS keyword declares a block-scoped variable?", ["var","let","const","dim"], "let"),
        ("Which HTML tag defines a table row?", ["<tr>","<td>","<table>","<row>"], "<tr>"),
        ("Which CSS property changes font size?", ["font-size","text-size","size","font"], "font-size"),
        ("Which event occurs when a user clicks on an element?", ["onclick","onhover","onchange","onmouse"], "onclick"),
        ("Which JS function converts number to string?", ["toString()","string()","convert()","Number()"], "toString()"),
        ("Which CSS unit is relative to viewport width?", ["vw","px","em","pt"], "vw"),
        ("Which HTML element is used for unordered lists?", ["<ul>","<ol>","<li>","<list>"], "<ul>"),
        ("Which JS operator is used for strict equality?", ["==","===","!=","!=="], "==="),
        ("Which method adds element to end of array in JS?", ["push()","append()","insert()","add()"], "push()"),
        ("Which CSS property changes background color?", ["background-color","bgcolor","color","background"], "background-color"),
        ("Which JS method removes last element from array?", ["pop()","remove()","delete()","shift()"], "pop()"),
        ("Which HTML tag is used for headings?", ["<h1>","<head>","<heading>","<h>"], "<h1>"),
        ("Which CSS property aligns text?", ["text-align","align","font-align","text-position"], "text-align"),
        ("Which JS loop is best when number of iterations is known?", ["for","while","do-while","foreach"], "for"),
        ("Which HTML attribute specifies image alternative text?", ["alt","src","title","name"], "alt"),
        ("Which method in JS adds element to beginning of array?", ["unshift()","push()","prepend()","addFirst()"], "unshift()"),
        ("Which tag is used to create a form in HTML?", ["<form>","<input>","<fieldset>","<f>"], "<form>"),
        ("Which CSS property changes element visibility?", ["visibility","display","opacity","hidden"], "visibility"),

        # 25 Descriptive
        ("Explain the difference between inline, block, and inline-block elements in HTML.", None, None),
        ("Describe how CSS specificity works.", None, None),
        ("Explain JavaScript closures with an example.", None, None),
        ("Describe the difference between == and === in JS.", None, None),
        ("Explain responsive web design.", None, None),
        ("Describe CSS Flexbox layout.", None, None),
        ("Explain CSS Grid system.", None, None),
        ("Describe how to optimize website loading speed.", None, None),
        ("Explain event delegation in JS.", None, None),
        ("Describe DOM manipulation with JS.", None, None),
        ("Explain difference between var, let, and const in JS.", None, None),
        ("Describe how to create forms in HTML.", None, None),
        ("Explain localStorage and sessionStorage in JS.", None, None),
        ("Describe difference between relative, absolute, and fixed positioning in CSS.", None, None),
        ("Explain semantic HTML.", None, None),
        ("Describe accessibility considerations in web development.", None, None),
        ("Explain how to validate forms with JavaScript.", None, None),
        ("Describe difference between GET and POST methods.", None, None),
        ("Explain CSS transitions and animations.", None, None),
        ("Describe responsive images and the <picture> tag.", None, None),
        ("Explain difference between inline CSS and external stylesheet.", None, None),
        ("Describe how to implement a sticky header.", None, None),
        ("Explain difference between CSS classes and IDs.", None, None),
        ("Describe client-side vs server-side rendering.", None, None),
        ("Explain difference between block-level and inline elements.", None, None),
    ],

    "Machine Learning Engineer": [
        # 25 MCQs
        ("Which algorithm is used for supervised learning?", ["Linear Regression","KMeans","PCA","Apriori"], "Linear Regression"),
        ("Which is unsupervised learning algorithm?", ["KMeans","Logistic Regression","Decision Tree","SVM"], "KMeans"),
        ("Which metric is used for regression evaluation?", ["Accuracy","MSE","F1-score","Precision"], "MSE"),
        ("Which metric is used for classification?", ["Accuracy","MSE","RMSE","Variance"], "Accuracy"),
        ("Which library is used for ML in Python?", ["sklearn","numpy","matplotlib","pandas"], "sklearn"),
        ("Which function splits data into train and test?", ["train_test_split()","split()","divide()","partition()"], "train_test_split()"),
        ("Which method prevents overfitting?", ["Regularization","Normalization","Scaling","Encoding"], "Regularization"),
        ("Which method is used to reduce dimensionality?", ["PCA","SVD","LDA","KMeans"], "PCA"),
        ("Which algorithm is used for clustering?", ["KMeans","Linear Regression","Decision Tree","Logistic Regression"], "KMeans"),
        ("Which loss function is used for regression?", ["MSE","CrossEntropy","Hinge","LogLoss"], "MSE"),
        ("Which loss function is used for classification?", ["CrossEntropy","MSE","RMSE","Variance"], "CrossEntropy"),
        ("Which method standardizes features?", ["StandardScaler","MinMaxScaler","LabelEncoder","OneHotEncoder"], "StandardScaler"),
        ("Which is used for one-hot encoding?", ["OneHotEncoder","LabelEncoder","StandardScaler","MinMaxScaler"], "OneHotEncoder"),
        ("Which method encodes labels?", ["LabelEncoder","OneHotEncoder","MinMaxScaler","StandardScaler"], "LabelEncoder"),
        ("Which is a tree-based model?", ["Random Forest","Linear Regression","KMeans","PCA"], "Random Forest"),
        ("Which kernel is used in SVM for non-linear?", ["RBF","Linear","Poly","Sigmoid"], "RBF"),
        ("Which technique reduces variance?", ["Bagging","Boosting","Regularization","Scaling"], "Bagging"),
        ("Which technique reduces bias?", ["Boosting","Bagging","Regularization","Scaling"], "Boosting"),
        ("Which is an ensemble method?", ["Random Forest","Linear Regression","KMeans","PCA"], "Random Forest"),
        ("Which metric measures classification imbalance?", ["F1-score","Accuracy","MSE","RMSE"], "F1-score"),
        ("Which is used for NLP preprocessing?", ["Tokenization","Scaling","PCA","Encoding"], "Tokenization"),
        ("Which is a deep learning library?", ["TensorFlow","sklearn","numpy","matplotlib"], "TensorFlow"),
        ("Which activation function is used in neural networks?", ["ReLU","Linear","Sigmoid","Softmax"], "ReLU"),
        ("Which optimizer is commonly used?", ["Adam","SGD","RMSProp","All"], "Adam"),
        ("Which method prevents gradient explosion?", ["Gradient Clipping","Regularization","Scaling","Normalization"], "Gradient Clipping"),

        # 25 Descriptive
        ("Explain supervised vs unsupervised learning.", None, None),
        ("Describe linear regression and its assumptions.", None, None),
        ("Explain logistic regression and classification.", None, None),
        ("Describe decision tree algorithm.", None, None),
        ("Explain random forest ensemble method.", None, None),
        ("Describe gradient boosting.", None, None),
        ("Explain KMeans clustering.", None, None),
        ("Describe PCA for dimensionality reduction.", None, None),
        ("Explain bias and variance tradeoff.", None, None),
        ("Describe cross-validation techniques.", None, None),
        ("Explain evaluation metrics for regression.", None, None),
        ("Describe evaluation metrics for classification.", None, None),
        ("Explain feature scaling methods.", None, None),
        ("Describe one-hot encoding and label encoding.", None, None),
        ("Explain hyperparameter tuning.", None, None),
        ("Describe neural network basics.", None, None),
        ("Explain activation functions in deep learning.", None, None),
        ("Describe optimizers in neural networks.", None, None),
        ("Explain overfitting and underfitting remedies.", None, None),
        ("Describe regularization techniques.", None, None),
        ("Explain tokenization in NLP.", None, None),
        ("Describe word embeddings.", None, None),
        ("Explain convolutional neural networks.", None, None),
        ("Describe recurrent neural networks.", None, None),
        ("Explain model evaluation techniques.", None, None),
    ],

    "AI Engineer": [
        # 25 MCQs
        ("Which is a deep learning framework?", ["TensorFlow","scikit-learn","pandas","numpy"], "TensorFlow"),
        ("Which model is used for NLP?", ["Transformer","CNN","RNN","KMeans"], "Transformer"),
        ("Which task involves image recognition?", ["Computer Vision","NLP","Clustering","Regression"], "Computer Vision"),
        ("Which is a type of neural network?", ["CNN","Linear Regression","Decision Tree","SVM"], "CNN"),
        ("Which optimizer is commonly used in deep learning?", ["Adam","SGD","RMSProp","All"], "Adam"),
        ("Which activation function outputs 0 or 1?", ["Sigmoid","ReLU","Tanh","Softmax"], "Sigmoid"),
        ("Which layer reduces input dimensions?", ["Pooling","Dense","Conv","Dropout"], "Pooling"),
        ("Which model generates text?", ["GPT","Random Forest","Linear Regression","KMeans"], "GPT"),
        ("Which NLP task extracts meaning?", ["Semantic Analysis","Clustering","Regression","Classification"], "Semantic Analysis"),
        ("Which model is used for machine translation?", ["Transformer","CNN","SVM","Decision Tree"], "Transformer"),
        ("Which method prevents overfitting in neural networks?", ["Dropout","Scaling","Standardization","PCA"], "Dropout"),
        ("Which loss function is used for classification?", ["CrossEntropy","MSE","RMSE","Variance"], "CrossEntropy"),
        ("Which activation function outputs negative values?", ["Tanh","ReLU","Sigmoid","Softmax"], "Tanh"),
        ("Which model uses attention mechanism?", ["Transformer","CNN","RNN","SVM"], "Transformer"),
        ("Which is used for text tokenization?", ["Tokenizer","Scaler","PCA","LabelEncoder"], "Tokenizer"),
        ("Which method is used for sequence modeling?", ["RNN","CNN","SVM","KMeans"], "RNN"),
        ("Which library is used for computer vision?", ["OpenCV","sklearn","pandas","matplotlib"], "OpenCV"),
        ("Which layer prevents overfitting?", ["Dropout","Dense","Pooling","Conv"], "Dropout"),
        ("Which optimizer uses momentum?", ["SGD","Adam","RMSProp","All"], "SGD"),
        ("Which NLP library is used for transformers?", ["HuggingFace","NLTK","Spacy","TextBlob"], "HuggingFace"),
        ("Which model is autoregressive?", ["GPT","CNN","RNN","Random Forest"], "GPT"),
        ("Which is used for token embedding?", ["Word2Vec","PCA","SVD","KMeans"], "Word2Vec"),
        ("Which task involves sentiment analysis?", ["NLP","Computer Vision","Clustering","Regression"], "NLP"),
        ("Which method updates weights in neural network?", ["Backpropagation","Gradient Descent","Forward Propagation","All"], "Backpropagation"),
        ("Which layer reduces overfitting by random disabling neurons?", ["Dropout","Dense","Conv","Pooling"], "Dropout"),

        # 25 Descriptive
        ("Explain NLP and its applications.", None, None),
        ("Describe transformers and attention mechanism.", None, None),
        ("Explain GPT models.", None, None),
        ("Describe CNNs in computer vision.", None, None),
        ("Explain RNNs and sequence modeling.", None, None),
        ("Describe activation functions.", None, None),
        ("Explain optimizers used in deep learning.", None, None),
        ("Describe overfitting and its remedies.", None, None),
        ("Explain computer vision tasks.", None, None),
        ("Describe tokenization in NLP.", None, None),
        ("Explain word embeddings.", None, None),
        ("Describe sentiment analysis process.", None, None),
        ("Explain machine translation using transformers.", None, None),
        ("Describe dropout and regularization.", None, None),
        ("Explain sequence-to-sequence models.", None, None),
        ("Describe attention mechanism in detail.", None, None),
        ("Explain backpropagation algorithm.", None, None),
        ("Describe supervised vs unsupervised learning in AI.", None, None),
        ("Explain evaluation metrics for AI models.", None, None),
        ("Describe GPT-based text generation.", None, None),
        ("Explain fine-tuning transformers.", None, None),
        ("Describe AI model deployment.", None, None),
        ("Explain transfer learning.", None, None),
        ("Describe CNN vs RNN differences.", None, None),
        ("Explain multi-head attention.", None, None),
    ],

    "Cloud Engineer": [
        # 25 MCQs
        ("Which is a cloud provider?", ["AWS","Python","TensorFlow","React"], "AWS"),
        ("Which is an IaaS platform?", ["EC2","S3","Lambda","DynamoDB"], "EC2"),
        ("Which is a PaaS offering?", ["Heroku","EC2","S3","VPC"], "Heroku"),
        ("Which is SaaS?", ["Salesforce","EC2","S3","Lambda"], "Salesforce"),
        ("Which AWS service is object storage?", ["S3","EC2","Lambda","VPC"], "S3"),
        ("Which service is compute?", ["EC2","S3","Lambda","RDS"], "EC2"),
        ("Which AWS service is serverless?", ["Lambda","EC2","S3","VPC"], "Lambda"),
        ("Which service provides VPC?", ["VPC","EC2","S3","Lambda"], "VPC"),
        ("Which service is used for relational DB?", ["RDS","S3","EC2","Lambda"], "RDS"),
        ("Which AWS tool is for deployment automation?", ["CloudFormation","S3","EC2","Lambda"], "CloudFormation"),
        ("Which security feature allows private subnets?", ["NACL","IAM","VPC","S3"], "VPC"),
        ("Which tool monitors AWS resources?", ["CloudWatch","CloudTrail","IAM","S3"], "CloudWatch"),
        ("Which service manages identity?", ["IAM","EC2","S3","Lambda"], "IAM"),
        ("Which is object storage type?", ["S3","EBS","EFS","Lambda"], "S3"),
        ("Which service is for content delivery?", ["CloudFront","EC2","S3","Lambda"], "CloudFront"),
        ("Which service is NoSQL database?", ["DynamoDB","RDS","S3","EC2"], "DynamoDB"),
        ("Which AWS service is messaging?", ["SNS","S3","EC2","Lambda"], "SNS"),
        ("Which service is caching?", ["ElastiCache","S3","EC2","Lambda"], "ElastiCache"),
        ("Which service is for data warehouse?", ["Redshift","S3","EC2","Lambda"], "Redshift"),
        ("Which service is monitoring logs?", ["CloudTrail","EC2","S3","Lambda"], "CloudTrail"),
        ("Which service automates resource provisioning?", ["CloudFormation","EC2","S3","Lambda"], "CloudFormation"),
        ("Which service is scalable compute?", ["EC2","Lambda","S3","VPC"], "EC2"),
        ("Which service provides managed Kubernetes?", ["EKS","EC2","S3","Lambda"], "EKS"),
        ("Which service provides serverless API?", ["API Gateway","EC2","S3","Lambda"], "API Gateway"),

        # 25 Descriptive
        ("Explain IaaS, PaaS, SaaS with examples.", None, None),
        ("Describe AWS EC2 service.", None, None),
        ("Explain S3 storage service.", None, None),
        ("Describe AWS Lambda.", None, None),
        ("Explain VPC and subnets.", None, None),
        ("Describe RDS service.", None, None),
        ("Explain CloudFormation templates.", None, None),
        ("Describe IAM users and roles.", None, None),
        ("Explain CloudFront for CDN.", None, None),
        ("Describe DynamoDB features.", None, None),
        ("Explain SNS and messaging.", None, None),
        ("Describe ElastiCache usage.", None, None),
        ("Explain Redshift and data warehousing.", None, None),
        ("Describe monitoring with CloudWatch.", None, None),
        ("Explain logging with CloudTrail.", None, None),
        ("Describe auto-scaling in AWS.", None, None),
        ("Explain API Gateway usage.", None, None),
        ("Describe EKS and Kubernetes management.", None, None),
        ("Explain serverless architecture.", None, None),
        ("Describe AWS security best practices.", None, None),
        ("Explain backup and disaster recovery.", None, None),
        ("Describe deployment strategies in AWS.", None, None),
        ("Explain cost optimization in cloud.", None, None),
        ("Describe AWS regions and availability zones.", None, None),
        ("Explain cloud migration strategies.", None, None),
    ],
})

# ------------------- REMAINING NON-TECHNICAL ROLES -------------------

NON_TECHNICAL_QUESTIONS.update({

    "Business Analyst": [
        # 25 MCQs
        ("Which technique identifies business strengths?", ["SWOT","Regression","Clustering","Coding"], "SWOT"),
        ("Which document describes business requirements?", ["BRD","Resume","Invoice","Report"], "BRD"),
        ("Which diagram represents system behavior?", ["Use Case","ERD","Gantt","Flowchart"], "Use Case"),
        ("Which tool is used for wireframing?", ["Balsamiq","Excel","Python","PowerPoint"], "Balsamiq"),
        ("Which is part of GAP analysis?", ["Current vs Future","Coding","Regression","Testing"], "Current vs Future"),
        ("Which KPI is financial metric?", ["ROI","Python","HTML","CSS"], "ROI"),
        ("Which diagram shows process flow?", ["Flowchart","Pie chart","Histogram","Table"], "Flowchart"),
        ("Which is stakeholder analysis?", ["Identify stakeholders","Write code","Design website","Deploy model"], "Identify stakeholders"),
        ("Which is requirement elicitation?", ["Gather needs","Python","Excel","Java"], "Gather needs"),
        ("Which tool creates BRD?", ["Word","Python","Excel","PowerPoint"], "Word"),
        ("Which is part of process modeling?", ["UML","SQL","Python","HTML"], "UML"),
        ("Which is business analysis technique?", ["SWOT","CNN","KMeans","TensorFlow"], "SWOT"),
        ("Which is use case diagram?", ["UML","Excel","Python","Word"], "UML"),
        ("Which is requirement traceability?", ["Tracking requirements","Coding","Testing","Design"], "Tracking requirements"),
        ("Which is BRD review step?", ["Validation","Deployment","Testing","Debugging"], "Validation"),
        ("Which method models business process?", ["BPMN","Python","Excel","Java"], "BPMN"),
        ("Which is key part of BA role?", ["Requirement gathering","Python coding","Designing UI","Testing"], "Requirement gathering"),
        ("Which tool helps in SWOT?", ["Excel","Python","TensorFlow","AWS"], "Excel"),
        ("Which is part of KPI tracking?", ["Metrics","Coding","Testing","Design"], "Metrics"),
        ("Which is process mapping?", ["Flowcharting","Python","HTML","CSS"], "Flowcharting"),
        ("Which is requirement prioritization?", ["MoSCoW","Python","HTML","CSS"], "MoSCoW"),
        ("Which is stakeholder meeting?", ["Discussion","Coding","Testing","Debugging"], "Discussion"),
        ("Which is part of BA documentation?", ["BRD","Python","HTML","CSS"], "BRD"),
        ("Which is gap analysis step?", ["Identify gaps","Python","HTML","CSS"], "Identify gaps"),
        ("Which is feasibility study?", ["Analyze viability","Coding","Testing","Design"], "Analyze viability"),

        # 25 Descriptive
        ("Explain SWOT analysis.", None, None),
        ("Describe requirement gathering.", None, None),
        ("Explain BRD creation.", None, None),
        ("Describe process modeling techniques.", None, None),
        ("Explain stakeholder analysis.", None, None),
        ("Describe GAP analysis process.", None, None),
        ("Explain KPI tracking.", None, None),
        ("Describe use case diagrams.", None, None),
        ("Explain requirement prioritization.", None, None),
        ("Describe feasibility study.", None, None),
        ("Explain process flow diagrams.", None, None),
        ("Describe business rules documentation.", None, None),
        ("Explain workflow analysis.", None, None),
        ("Describe data modeling techniques.", None, None),
        ("Explain BA role in project lifecycle.", None, None),
        ("Describe functional vs non-functional requirements.", None, None),
        ("Explain BRD validation process.", None, None),
        ("Describe requirement traceability matrix.", None, None),
        ("Explain stakeholder communication plan.", None, None),
        ("Describe business process improvement.", None, None),
        ("Explain cost-benefit analysis in BA.", None, None),
        ("Describe gap closure strategies.", None, None),
        ("Explain metrics and KPI dashboards.", None, None),
        ("Describe change management in BA.", None, None),
        ("Explain documentation standards for BA.", None, None),
    ],

    "Digital Marketing Executive": [
        # 25 MCQs
        ("Which technique improves search ranking?", ["SEO","Python","HTML","CSS"], "SEO"),
        ("Which platform is for ads?", ["Google Ads","AWS","Python","Excel"], "Google Ads"),
        ("Which metric measures website traffic?", ["Analytics","Python","HTML","CSS"], "Analytics"),
        ("Which campaign type is email?", ["Email Marketing","Python","HTML","CSS"], "Email Marketing"),
        ("Which metric measures ROI?", ["ROI","Python","HTML","CSS"], "ROI"),
        ("Which metric tracks click rate?", ["CTR","Python","HTML","CSS"], "CTR"),
        ("Which platform manages social media posts?", ["Hootsuite","Python","Excel","Word"], "Hootsuite"),
        ("Which is part of content marketing?", ["Blog","Python","HTML","CSS"], "Blog"),
        ("Which tool tracks conversions?", ["Google Analytics","Python","Excel","Word"], "Google Analytics"),
        ("Which metric shows engagement?", ["Engagement Rate","Python","HTML","CSS"], "Engagement Rate"),
        ("Which technique improves PPC campaigns?", ["Keyword Research","Python","HTML","CSS"], "Keyword Research"),
        ("Which tool manages email campaigns?", ["Mailchimp","Python","HTML","CSS"], "Mailchimp"),
        ("Which platform is for paid ads?", ["Google Ads","Python","HTML","CSS"], "Google Ads"),
        ("Which metric shows bounce rate?", ["Bounce Rate","Python","HTML","CSS"], "Bounce Rate"),
        ("Which technique increases organic traffic?", ["SEO","Python","HTML","CSS"], "SEO"),
        ("Which content type boosts engagement?", ["Video","Python","HTML","CSS"], "Video"),
        ("Which tool tracks SEO ranking?", ["SEMRush","Python","Excel","Word"], "SEMRush"),
        ("Which platform manages multiple social media accounts?", ["Hootsuite","Python","Excel","Word"], "Hootsuite"),
        ("Which metric tracks impressions?", ["Impressions","Python","HTML","CSS"], "Impressions"),
        ("Which technique optimizes content for search engines?", ["SEO","Python","HTML","CSS"], "SEO"),
        ("Which is part of analytics dashboard?", ["Metrics","Python","HTML","CSS"], "Metrics"),
        ("Which metric tracks conversion rate?", ["Conversion Rate","Python","HTML","CSS"], "Conversion Rate"),
        ("Which strategy improves email open rate?", ["Subject Line Optimization","Python","HTML","CSS"], "Subject Line Optimization"),
        ("Which metric tracks customer retention?", ["Retention Rate","Python","HTML","CSS"], "Retention Rate"),
        ("Which tool measures campaign performance?", ["Google Analytics","Python","Excel","Word"], "Google Analytics"),

        # 25 Descriptive
        ("Explain SEO and its importance.", None, None),
        ("Describe PPC advertising.", None, None),
        ("Explain social media marketing.", None, None),
        ("Describe email marketing strategies.", None, None),
        ("Explain content marketing.", None, None),
        ("Describe conversion rate optimization.", None, None),
        ("Explain Google Analytics metrics.", None, None),
        ("Describe keyword research process.", None, None),
        ("Explain engagement metrics.", None, None),
        ("Describe bounce rate analysis.", None, None),
        ("Explain ROI in digital marketing.", None, None),
        ("Describe ad targeting techniques.", None, None),
        ("Explain marketing funnel stages.", None, None),
        ("Describe audience segmentation.", None, None),
        ("Explain A/B testing in campaigns.", None, None),
        ("Describe influencer marketing.", None, None),
        ("Explain content strategy creation.", None, None),
        ("Describe SEO tools usage.", None, None),
        ("Explain email campaign optimization.", None, None),
        ("Describe metrics for social media.", None, None),
        ("Explain paid vs organic traffic.", None, None),
        ("Describe landing page optimization.", None, None),
        ("Explain marketing automation tools.", None, None),
        ("Describe lead generation techniques.", None, None),
        ("Explain digital branding strategies.", None, None),
    ],

    "Content Writer": [
        # 25 MCQs
        ("Which is essential for blog writing?", ["SEO","Python","HTML","CSS"], "SEO"),
        ("Which checks grammar automatically?", ["Grammarly","Python","Excel","Word"], "Grammarly"),
        ("Which type of content persuades readers?", ["Copywriting","Python","HTML","CSS"], "Copywriting"),
        ("Which content focuses on storytelling?", ["Blog","Python","HTML","CSS"], "Blog"),
        ("Which is part of content strategy?", ["Audience Research","Python","HTML","CSS"], "Audience Research"),
        ("Which metric tracks readability?", ["Flesch Score","Python","HTML","CSS"], "Flesch Score"),
        ("Which tool helps in plagiarism check?", ["Turnitin","Python","Excel","Word"], "Turnitin"),
        ("Which content is optimized for SEO?", ["Web Content","Python","HTML","CSS"], "Web Content"),
        ("Which content aims to inform?", ["Educational","Python","HTML","CSS"], "Educational"),
        ("Which tone builds trust?", ["Professional","Python","HTML","CSS"], "Professional"),
        ("Which content is persuasive?", ["Sales Copy","Python","HTML","CSS"], "Sales Copy"),
        ("Which is a long-form content type?", ["Whitepaper","Python","HTML","CSS"], "Whitepaper"),
        ("Which platform is for article publishing?", ["Medium","Python","HTML","CSS"], "Medium"),
        ("Which metric tracks engagement?", ["Time on Page","Python","HTML","CSS"], "Time on Page"),
        ("Which writing improves readability?", ["Simple Language","Python","HTML","CSS"], "Simple Language"),
        ("Which technique improves SEO ranking?", ["Keyword Placement","Python","HTML","CSS"], "Keyword Placement"),
        ("Which content type improves brand awareness?", ["Blog","Python","HTML","CSS"], "Blog"),
        ("Which metric measures content reach?", ["Impressions","Python","HTML","CSS"], "Impressions"),
        ("Which tool helps in headline optimization?", ["CoSchedule","Python","HTML","CSS"], "CoSchedule"),
        ("Which type of content engages social media?", ["Visual Content","Python","HTML","CSS"], "Visual Content"),
        ("Which checks spelling errors?", ["Spellcheck","Python","Excel","Word"], "Spellcheck"),
        ("Which content requires research?", ["Educational","Python","HTML","CSS"], "Educational"),
        ("Which tool helps in readability analysis?", ["Hemingway","Python","HTML","CSS"], "Hemingway"),
        ("Which technique improves content flow?", ["Outline Creation","Python","HTML","CSS"], "Outline Creation"),
        ("Which writing style suits blogs?", ["Conversational","Python","HTML","CSS"], "Conversational"),

        # 25 Descriptive
        ("Explain the importance of SEO in writing.", None, None),
        ("Describe how to write engaging blogs.", None, None),
        ("Explain copywriting techniques.", None, None),
        ("Describe content planning strategies.", None, None),
        ("Explain audience analysis for content.", None, None),
        ("Describe tone and style in writing.", None, None),
        ("Explain structure of a professional article.", None, None),
        ("Describe proofreading methods.", None, None),
        ("Explain content research techniques.", None, None),
        ("Describe keyword optimization.", None, None),
        ("Explain long-form vs short-form content.", None, None),
        ("Describe storytelling in writing.", None, None),
        ("Explain content marketing strategies.", None, None),
        ("Describe writing for social media.", None, None),
        ("Explain readability scoring.", None, None),
        ("Describe plagiarism prevention.", None, None),
        ("Explain headline writing techniques.", None, None),
        ("Describe content repurposing.", None, None),
        ("Explain SEO-friendly writing.", None, None),
        ("Describe blog post structure.", None, None),
        ("Explain editing and proofreading steps.", None, None),
        ("Describe persuasive writing.", None, None),
        ("Explain call-to-action writing.", None, None),
        ("Describe content promotion strategies.", None, None),
        ("Explain metrics for content success.", None, None),
    ],

    "Customer Support Executive": [
        # 25 MCQs
        ("Which skill is crucial for support?", ["Empathy","Python","HTML","CSS"], "Empathy"),
        ("Which tool manages support tickets?", ["CRM","Python","Excel","Word"], "CRM"),
        ("Which is part of SLA?", ["Response Time","Python","HTML","CSS"], "Response Time"),
        ("Which metric measures customer satisfaction?", ["CSAT","Python","HTML","CSS"], "CSAT"),
        ("Which skill helps in conflict resolution?", ["Negotiation","Python","HTML","CSS"], "Negotiation"),
        ("Which method handles complaints?", ["Ticketing System","Python","Excel","Word"], "Ticketing System"),
        ("Which is part of call etiquette?", ["Politeness","Python","HTML","CSS"], "Politeness"),
        ("Which metric tracks resolution speed?", ["Time to Resolution","Python","HTML","CSS"], "Time to Resolution"),
        ("Which software tracks interactions?", ["CRM","Python","Excel","Word"], "CRM"),
        ("Which approach improves retention?", ["Follow-ups","Python","HTML","CSS"], "Follow-ups"),
        ("Which skill aids active listening?", ["Communication","Python","HTML","CSS"], "Communication"),
        ("Which method tracks feedback?", ["Surveys","Python","Excel","Word"], "Surveys"),
        ("Which is part of customer onboarding?", ["Guidance","Python","HTML","CSS"], "Guidance"),
        ("Which approach manages difficult clients?", ["Empathy","Python","HTML","CSS"], "Empathy"),
        ("Which tool reports ticket stats?", ["CRM","Python","Excel","Word"], "CRM"),
        ("Which is part of escalation process?", ["Prioritization","Python","HTML","CSS"], "Prioritization"),
        ("Which metric tracks first response time?", ["FRT","Python","HTML","CSS"], "FRT"),
        ("Which approach handles multiple tickets?", ["Multitasking","Python","HTML","CSS"], "Multitasking"),
        ("Which skill builds rapport?", ["Empathy","Python","HTML","CSS"], "Empathy"),
        ("Which tool logs interactions?", ["CRM","Python","Excel","Word"], "CRM"),
        ("Which approach ensures SLA compliance?", ["Monitoring","Python","HTML","CSS"], "Monitoring"),
        ("Which method handles refunds?", ["Policy Adherence","Python","HTML","CSS"], "Policy Adherence"),
        ("Which skill manages frustration?", ["Patience","Python","HTML","CSS"], "Patience"),
        ("Which approach improves customer experience?", ["Feedback Implementation","Python","HTML","CSS"], "Feedback Implementation"),
        ("Which metric tracks ticket backlog?", ["Open Tickets","Python","HTML","CSS"], "Open Tickets"),

        # 25 Descriptive
        ("Explain active listening in support.", None, None),
        ("Describe handling customer complaints.", None, None),
        ("Explain ticketing systems.", None, None),
        ("Describe SLA and its importance.", None, None),
        ("Explain conflict resolution techniques.", None, None),
        ("Describe escalation procedures.", None, None),
        ("Explain customer onboarding.", None, None),
        ("Describe call etiquette rules.", None, None),
        ("Explain CRM software usage.", None, None),
        ("Describe customer satisfaction metrics.", None, None),
        ("Explain retention strategies.", None, None),
        ("Describe effective communication skills.", None, None),
        ("Explain feedback collection methods.", None, None),
        ("Describe complaint handling steps.", None, None),
        ("Explain managing difficult clients.", None, None),
        ("Describe first response time improvement.", None, None),
        ("Explain multitasking in support.", None, None),
        ("Describe rapport building techniques.", None, None),
        ("Explain monitoring for SLA compliance.", None, None),
        ("Describe refund handling process.", None, None),
        ("Explain ticket backlog management.", None, None),
        ("Describe patience and stress management.", None, None),
        ("Explain tools for interaction logging.", None, None),
        ("Describe feedback implementation process.", None, None),
        ("Explain enhancing overall customer experience.", None, None),
    ],

    "Operations Executive": [
        # 25 MCQs
        ("Which activity is part of operations?", ["Planning","Python","HTML","CSS"], "Planning"),
        ("Which tool helps in workflow management?", ["MS Project","Python","Excel","Word"], "MS Project"),
        ("Which metric tracks process efficiency?", ["Throughput","Python","HTML","CSS"], "Throughput"),
        ("Which is part of reporting?", ["Dashboards","Python","HTML","CSS"], "Dashboards"),
        ("Which process ensures task completion?", ["Execution","Python","HTML","CSS"], "Execution"),
        ("Which tool tracks deadlines?", ["MS Project","Python","Excel","Word"], "MS Project"),
        ("Which metric measures productivity?", ["Output per hour","Python","HTML","CSS"], "Output per hour"),
        ("Which process manages resources?", ["Resource Allocation","Python","HTML","CSS"], "Resource Allocation"),
        ("Which activity involves documentation?", ["Recording","Python","HTML","CSS"], "Recording"),
        ("Which tool tracks operations KPIs?", ["Dashboard","Python","Excel","Word"], "Dashboard"),
        ("Which metric measures workflow delays?", ["Lead Time","Python","HTML","CSS"], "Lead Time"),
        ("Which process ensures quality?", ["Quality Assurance","Python","HTML","CSS"], "Quality Assurance"),
        ("Which tool monitors operations?", ["ERP System","Python","Excel","Word"], "ERP System"),
        ("Which metric tracks execution time?", ["Cycle Time","Python","HTML","CSS"], "Cycle Time"),
        ("Which activity ensures compliance?", ["Audit","Python","HTML","CSS"], "Audit"),
        ("Which process optimizes operations?", ["Process Improvement","Python","HTML","CSS"], "Process Improvement"),
        ("Which tool schedules tasks?", ["MS Project","Python","Excel","Word"], "MS Project"),
        ("Which metric measures resource utilization?", ["Efficiency","Python","HTML","CSS"], "Efficiency"),
        ("Which activity manages vendor contracts?", ["Procurement","Python","HTML","CSS"], "Procurement"),
        ("Which process handles inventory?", ["Inventory Management","Python","HTML","CSS"], "Inventory Management"),
        ("Which tool tracks operational costs?", ["ERP System","Python","Excel","Word"], "ERP System"),
        ("Which metric tracks SLA adherence?", ["Compliance Rate","Python","HTML","CSS"], "Compliance Rate"),
        ("Which activity manages risk?", ["Risk Management","Python","HTML","CSS"], "Risk Management"),
        ("Which process ensures smooth workflow?", ["Operations Coordination","Python","HTML","CSS"], "Operations Coordination"),
        ("Which metric evaluates process performance?", ["KPI","Python","HTML","CSS"], "KPI"),

        # 25 Descriptive
        ("Explain planning in operations.", None, None),
        ("Describe execution and monitoring.", None, None),
        ("Explain workflow management.", None, None),
        ("Describe resource allocation.", None, None),
        ("Explain reporting and dashboards.", None, None),
        ("Describe quality assurance processes.", None, None),
        ("Explain process improvement.", None, None),
        ("Describe operational KPIs.", None, None),
        ("Explain inventory management.", None, None),
        ("Describe procurement process.", None, None),
        ("Explain cycle time measurement.", None, None),
        ("Describe audit and compliance.", None, None),
        ("Explain ERP system usage.", None, None),
        ("Describe risk management strategies.", None, None),
        ("Explain vendor management.", None, None),
        ("Describe task scheduling.", None, None),
        ("Explain SLA adherence monitoring.", None, None),
        ("Describe throughput and efficiency.", None, None),
        ("Explain documentation in operations.", None, None),
        ("Describe coordination across teams.", None, None),
        ("Explain operational cost tracking.", None, None),
        ("Describe metrics for performance evaluation.", None, None),
        ("Explain reporting accuracy.", None, None),
        ("Describe handling workflow delays.", None, None),
        ("Explain overall process optimization.", None, None),
    ],
})

